language: python
python:
    - "3.5"
before_install:
    - pip install vcfpy==0.12.0
    - pip install pysam
    - pip install pandas
    - pip install gtfparse
    - pip install testfixtures
install: true
script:
    - python3 -m unittest discover -v
